Contact page & About us
ComicScrip/lyon-react-mars22-p2g5 pull request #39
Opened 2022-04-21 07:37 UTC by timonicolaux

Finished user story 1 of contact page & about us

2022-04-21 09:52 UTC, NycoChavanoud requested changes
1- ATTENTION : la pull request doit être faite sur DEV et non sur Main...
2- niveau code il à l'air propre donc ok.
3- Le visuel n'est pas conforme aux maquettes (sommaires quand meme..) Aucun Background. Merci vérifier les intégrations avant d'y mettre en prod..

2022-04-21 12:21 UTC, JBillault submitted a review, later dismissed

2022-04-22 12:23 UTC, JBillault approved these changes

2022-04-24 11:43 UTC, ComicScrip commented
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/16140010/164974765-b3c75b29-4bd3-4510-a39d-ae2ced1caeb0.png">

2022-04-24 11:49 UTC, ComicScrip requested changes

2022-04-24 11:49 UTC, ComicScrip commented on src/components/AboutUs.js
> +function AboutUs(props) {
Mal nommé

2022-04-24 11:49 UTC, ComicScrip commented on src/components/Carrousel.js
> +function Carrousel() {
Quelle est l'utilité de ce composant intermédiaire s'il ne fait qu'afficher un autre composant ?

2022-04-24 11:49 UTC, ComicScrip commented on src/components/DataSlider.js
> +import { v4 as uuidv4 } from 'uuid';
a quoi sert ce fichier ?

2022-04-24 16:08 UTC, timonicolaux commented on src/components/DataSlider.js
> +import { v4 as uuidv4 } from 'uuid';
C'était utilisé dans le tuto du carrousel pour générer de la fausse data il me semble je l'ai supprimé

2022-04-24 16:10 UTC, timonicolaux commented on src/components/Carrousel.js
> +function Carrousel() {
C'est la page de choix de catégories sur laquelle sera intégrée la barre de sélection + les composants des catégories de quizz, je l'ai renommée pour que ce soit plus explicite

2022-04-24 16:19 UTC, timonicolaux commented on src/components/AboutUs.js
> +function AboutUs(props) {
C'est à dire ? Il faut changer props pour un autre nom ?

2022-04-25 14:17 UTC, Claiirou approved these changes
ok

2022-04-25 15:27 UTC, closed without merging